http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/customers"
serviceEndpoints:
  httpbin:
    url: "http://localhost:3001/api/customer/"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - log:
          action:
            message: "books ${req.method}"
      - jwt:
          action:
            secretOrPublicKey: "the-secret-key"
            checkCredentialExistence: false
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - proxy:
          action:
            serviceEndpoint: httpbin
